zepben/ewb-sdk-python

src/zepben/cimbend/__init__.py, src/zepben/cimbend/cim/iec61970/base/core/connectivity_node.py, src/zepben/cimbend/cim/iec61970/base/core/equipment.py, src/zepben/cimbend/cim/iec61970/base/core/substation.py, src/zepben/cimbend/cim/iec61970/base/core/terminal.py, src/zepben/cimbend/cim/iec61970/base/wires/switch.py, src/zepben/cimbend/model/__init__.py, src/zepben/cimbend/model/phasedirection.py, src/zepben/cimbend/model/phases.py, src/zepben/cimbend/network/network.py, src/zepben/cimbend/network/tracing/__init__.py, src/zepben/cimbend/network/translator/network_cim2proto.py, src/zepben/cimbend/tracing/__init__.py, src/zepben/cimbend/tracing/connectivity.py, src/zepben/cimbend/tracing/phase_status.py, src/zepben/cimbend/tracing/phasing.py, src/zepben/cimbend/tracing/util.py, src/zepben/cimbend/traversals/__init__.py, src/zepben/cimbend/traversals/branch_recursive_tracing.py, src/zepben/cimbend/traversals/tracing.py, src/zepben/cimbend/traversals/tracker.py
=> Re-align tracing with java model

docs/babel.config.js, docs/docs/consumer.mdx, docs/docs/datamodel.mdx, docs/docs/services.mdx, docs/docs/tracing.mdx, docs/docusaurus.config.js, docs/sidebars.js, docs/src/theme/SearchBar/index.js
Fixed typos, changed links to docusaurus
=> SITE-50_Read-the-documentation-and-identify-typos-and-bugs

.coveragerc, .github/workflows/build.yml, .github/workflows/deploy-snapshot.yml, .github/workflows/release.yml, README.md, requirements.txt, setup.py, src/zepben/evolve/streaming/get/network_consumer.py, src/zepben/evolve/streaming/put/producer.py, test/run_streaming.py, tox.ini
=> Run build and tests inside tox

tox.ini
=> Fix coveralls submission

docs/package-lock.json, docs/package.json
Signed-off-by: Varun Ramani <varun.ramani@zepben.com>
=> Upgrade doc deps

docs/docusaurus.config.js, docs/package-lock.json, docs/package.json, docs/src/pages/index.tsx
Signed-off-by: Varun Ramani <varun.ramani@zepben.com>
=> Setup contextual search

test/services/__init__.py, test/services/network/__init__.py, test/services/network/test_energy_source_phase.py, test/services/network/test_network.py
Created the test for EnergySourcePhase service object
=> Created the test for EnergySourcePhase service object

test/cim/iec61970/base/wires/test_junction.py
Signed-off-by: Abdullah <abdullah.elahi@zepben.com>
=> Test for junction

test/services/common/test_base_service.py
Signed-off-by: Abdullah <abdullah.elahi@zepben.com>
=> ewb-597_test_base_service_update

README.md, docs/docs/datamodel.mdx, docs/versioned_docs/version-0.21.0/datamodel.mdx, docs/versioned_docs/version-0.22.0/datamodel.mdx
Signed-off-by: ryanjcoleman <ryan.coleman@zepben.com>
=> Fixed readme links, updated links to Discussions in doco

src/zepben/evolve/model/busbranch/bus_branch.py, test/busbranch/conftest.py, test/busbranch/test_bus_branch.py
- Added support for power electronics connections.
- Updated validation used in the create_bus_branch.
Signed-off-by: Roberto Marquez <roberto.marquez@zepben.com>
=> Updated create_bus_branch method

changelog.md, src/zepben/evolve/__init__.py, src/zepben/evolve/model/cim/iec61968/assetinfo/power_transformer_info.py, src/zepben/evolve/model/cim/iec61968/assetinfo/transformer_end_info.py, src/zepben/evolve/model/cim/iec61968/assetinfo/transformer_tank_info.py, src/zepben/evolve/model/cim/iec61970/base/wires/power_transformer.py, src/zepben/evolve/model/cim/iec61970/base/wires/transformer_star_impedance.py, src/zepben/evolve/services/common/reference_resolvers.py, src/zepben/evolve/services/common/resolver.py, src/zepben/evolve/services/network/translator/__init__.py, src/zepben/evolve/services/network/translator/network_cim2proto.py, src/zepben/evolve/services/network/translator/network_proto2cim.py, src/zepben/evolve/streaming/put/network_rpc.py, test/cim/constructor_validation.py, test/cim/iec61968/assetinfo/test_power_transformer_info.py, test/cim/iec61968/assetinfo/test_transformer_end_info.py, test/cim/iec61968/assetinfo/test_transformer_tank_info.py, test/cim/iec61970/base/wires/test_transformer_star_impedance.py, test/cim_creators.py, test/pb_creators.py, test/test_consumer.py
* Added CIM class TransformerStarImpedance.
* Added CIM class TransformerEndInfo.
* Added star_impedance property to PowerTransformer class.
* Added transformer_tank_infos property to PowerTransformerInfo class.
Signed-off-by: Roberto Marquez <roberto.marquez@zepben.com>
=> * Added CIM class TransformerTankInfo.

src/zepben/evolve/model/cim/iec61970/base/core/phase_code.py, src/zepben/evolve/model/cim/iec61970/base/wires/single_phase_kind.py, src/zepben/evolve/services/network/translator/network_proto2cim.py, test/cim/enum_validator.py, test/cim/iec61968/assetinfo/test_wire_material_kind.py, test/cim/iec61968/assets/test_streetlight_lamp_kind.py, test/cim/iec61968/customers/test_customer_kind.py, test/cim/iec61970/base/core/test_phase_code.py, test/cim/iec61970/base/diagramlayout/test_diagram_style.py, test/cim/iec61970/base/diagramlayout/test_orientation_kind.py, test/cim/iec61970/base/domain/__init__.py, test/cim/iec61970/base/domain/test_unit_symbol.py, test/cim/iec61970/base/wires/generation/production/test_battery_state_kind.py, test/cim/iec61970/base/wires/test_phase_shunt_connection_kind.py, test/cim/iec61970/base/wires/test_single_phase_kind.py, test/cim/iec61970/base/wires/test_vector_group.py, test/cim/iec61970/base/wires/test_winding_connection.py
=> EWB-818 - Added tests for cim vs epb enumm validation

changelog.md
=> EWB-799 - Changed `DiagramObject.style` to be a string [skip ci]

changelog.md, setup.py, src/zepben/evolve/model/cim/iec61968/metering/metering.py, src/zepben/evolve/services/network/network_service_comparator.py, src/zepben/evolve/services/network/translator/network_cim2proto.py, src/zepben/evolve/services/network/translator/network_proto2cim.py, test/cim/iec61968/metering/test_usage_point.py, test/cim_creators.py, test/pb_creators.py, test/services/network/test_network_service_comparator.py
=> EWB-826 - Added `isVirtual` and `connectionCategory` to `UsagePoint`

src/zepben/evolve/__init__.py, src/zepben/evolve/model/cim/iec61968/assetinfo/transformer_end_info.py, src/zepben/evolve/model/cim/iec61970/base/wires/transformer_star_impedance.py, src/zepben/evolve/model/resistance_reactance.py, test/cim/iec61968/assetinfo/test_transformer_end_info.py
Signed-off-by: cmacana <carlos.macana@zepben.com>
=> Added: calculate_resistance_reactance_from_tests & related tests

src/zepben/evolve/database/sqlite/writers/diagram_cim_writer.py, src/zepben/evolve/database/sqlite/writers/diagram_service_writer.py
Signed-off-by: Jimmy Tung <jimmy.tung@zepben.com>
=> created diagram_cim_writer and diagram_server_writer

.github/workflows/build.yml, .github/workflows/deploy-snapshot.yml, .github/workflows/release.yml, README.md, tox.ini
Signed-off-by: Jimmy Tung <jimmy.tung@zepben.com>
=> Enable codecov

changelog.md, setup.py, src/zepben/evolve/__init__.py, src/zepben/evolve/database/sqlite/readers/network_cim_reader.py, src/zepben/evolve/database/sqlite/tables/iec61970/base/wires/energyconnection_tables.py, src/zepben/evolve/database/sqlite/tables/iec61970/base/wires/generation/production_tables.py, src/zepben/evolve/database/sqlite/tables/iec61970/base/wires/transformer_tables.py, src/zepben/evolve/database/sqlite/tables/metadata_tables.py, src/zepben/evolve/database/sqlite/writers/network_cim_writer.py, src/zepben/evolve/model/cim/iec61968/infiec61968/__init__.py, src/zepben/evolve/model/cim/iec61968/infiec61968/infassetinfo/__init__.py, src/zepben/evolve/model/cim/iec61968/infiec61968/infassetinfo/transformer_construction_kind.py, src/zepben/evolve/model/cim/iec61968/infiec61968/infassetinfo/transformer_function_kind.py, src/zepben/evolve/model/cim/iec61970/base/wires/power_transformer.py, src/zepben/evolve/services/network/network_service_comparator.py, src/zepben/evolve/services/network/translator/network_cim2proto.py, src/zepben/evolve/services/network/translator/network_proto2cim.py, test/cim/iec61970/base/wires/test_power_transformer.py, test/database/sqlite/test_database_sqlite.py, test/services/network/test_network_service_comparator.py
=> EWB 775 Add Transformer Function Kind and Transformer Construction Kind

changelog.md, setup.py, src/zepben/evolve/database/sqlite/readers/network_cim_reader.py, src/zepben/evolve/database/sqlite/tables/iec61968/common_tables.py, src/zepben/evolve/database/sqlite/tables/metadata_tables.py, src/zepben/evolve/database/sqlite/writers/network_cim_writer.py, src/zepben/evolve/model/cim/iec61968/common/location.py, src/zepben/evolve/services/network/translator/network_cim2proto.py, src/zepben/evolve/services/network/translator/network_proto2cim.py, test/cim/iec61968/common/test_street_address.py, test/cim/iec61968/common/test_street_detail.py, test/cim/iec61968/common/test_town_detail.py, test/cim_creators.py, test/database/sqlite/schema_utils.py, test/database/sqlite/test_database_sqlite.py, test/pb_creators.py, test/services/network/translator/test_network_translator.py
=> Add StreetDetail

changelog.md, src/zepben/evolve/streaming/get/customer_consumer.py, src/zepben/evolve/streaming/get/diagram_consumer.py, src/zepben/evolve/streaming/get/network_consumer.py, src/zepben/evolve/streaming/grpc/grpc.py, test/streaming/get/mock_server.py, test/streaming/get/test_network_consumer.py
still in progress adding tests...
=> Add timeouts

src/zepben/evolve/streaming/grpc/connect.py
=> EWB-1322: Support optional conf_address parameter in connect_with_password

src/zepben/evolve/__init__.py, src/zepben/evolve/services/network/network_service.py, src/zepben/evolve/services/network/tracing/connectivity/terminal_connectivity_connected.py, src/zepben/evolve/services/network/tracing/connectivity/terminal_connectivity_internal.py, src/zepben/evolve/services/network/tracing/connectivity/transformer_phase_paths.py, src/zepben/evolve/services/network/tracing/connectivity/xy_candidate_phase_paths.py, src/zepben/evolve/services/network/tracing/phases/set_phases.py, test/network_fixtures.py, test/services/network/tracing/connectivity/__init__.py, test/services/network/tracing/connectivity/test_terminal_connectivity_connected.py, test/services/network/tracing/connectivity/test_terminal_connectivity_internal.py, test/services/network/tracing/phases/test_set_phases.py
=> PROJ-2476 - Aligned `SetPhases` with JVM changes

docs/docs/phases.mdx, docs/sidebars.js
=> PROJ-2408 - Added doco for phase and feeder direction changes.

changelog.md, src/zepben/evolve/__init__.py, src/zepben/evolve/database/sqlite/database_reader.py, src/zepben/evolve/services/network/tracing/feeder/feeder_direction.py, src/zepben/evolve/services/network/tracing/feeder/remove_direction.py, src/zepben/evolve/services/network/tracing/feeder/set_direction.py, src/zepben/evolve/services/network/tracing/tracing.py, src/zepben/evolve/services/network/tracing/traversals/branch_recursive_tracing.py, src/zepben/evolve/testing/test_network_builder.py, test/services/network/test_data/__init__.py, test/services/network/test_data/phase_swap_loop_network.py, test/services/network/tracing/feeder/__init__.py, test/services/network/tracing/feeder/direction_logger.py, test/services/network/tracing/feeder/test_feeder_direction.py, test/services/network/tracing/feeder/test_remove_direction.py, test/services/network/tracing/feeder/test_set_direction.py, test/services/network/tracing/test_tracing.py
=> PROJ-1952 - Added convenience classes `SetDirection` and `RemoveDirection` to set and remove feeder directions on a `NetworkService`.

src/zepben/evolve/services/network/tracing/phases/phase_step_tracker.py, src/zepben/evolve/services/network/tracing/phases/phase_trace.py
=> Determine if new phases have been visited properly.

changelog.md, src/zepben/evolve/services/network/tracing/phases/phase_step_tracker.py, test/services/network/tracing/phases/test_phase_step_tracker.py
=> EWB-1625: Fix bug in PhaseStepTracker and add tests for it

changelog.md, src/zepben/evolve/model/busbranch/bus_branch.py, test/busbranch/data/open_switch_between_different_voltages.py, test/busbranch/test_bus_branch.py
=> EWB-1523: Do not use switches when getting base voltage

changelog.md, src/zepben/evolve/model/busbranch/bus_branch.py, test/network_fixtures.py, test/services/network/tracing/phases/test_remove_phases.py
=> EWB-1754: Improve performance of bus branch creator

setup.py
Updates zepben.auth version to `0.10.0b2` to resolve dependency conflict in the new examples repo.
- None
- https://github.com/zepben/edith-sdk/pull/3
- https://github.com/zepben/pp-translator/pull/19
=> EWB-2597: Update auth version

changelog.md, setup.py, src/zepben/evolve/services/common/base_service.py, src/zepben/evolve/services/network/translator/__init__.py, src/zepben/evolve/streaming/get/consumer.py, src/zepben/evolve/streaming/get/customer_consumer.py, src/zepben/evolve/streaming/get/diagram_consumer.py, test/streaming/get/pb_creators.py, test/streaming/get/test_customer_consumer.py, test/streaming/get/test_diagram_consumer.py
Added consumer client functions for getDiagramObjects and getCustomersForContainer.
Also added functionality for getIdentifiedObjects, as that was not actually previously implemented.
Tests are not yet exhaustive - need more for getDiagramObjects and getCustomersForContainer, but will create a separate task for this.
These are always required, if you do not do them, reviewers will be angry:
These you can remove from the list if they are not applicable for this PR.
=> Ewb 3386 customer diagram rpcs

changelog.md, src/zepben/evolve/services/network/tracing/phases/phase_status.py, test/services/network/tracing/phases/test_phase_status.py
These are always required, if you do not do them, reviewers will be angry:
These you can remove from the list if they are not applicable for this PR.
=> PROJ-3407: Asking for the traced phases as a phase code when there are no nominal phases no longer throws.

CONTRIBUTING.md, changelog.md, src/zepben/evolve/streaming/get/network_consumer.py
Add missing class to nio type to cim
These are always required, if you do not do them, reviewers will be angry:
These you can remove from the list if they are not applicable for this PR.
=> Add missing nio type to network_consumer.py

docs/docusaurus.config.js
=> Fix docusaurus config

changelog.md, src/zepben/evolve/services/network/tracing/feeder/set_direction.py, test/services/network/tracing/feeder/test_set_direction.py
Fixed issue with SetDirection not tracing through non-substation transformers. 
Please leave a summary of the breaking changes here. This is useful for the reviewer, but also is useful for communication to the team when merged (e.g. you could copy and paste the summary into slack).
=> EWB-4112 Trace through non-substation transformers 

.gitignore, changelog.md, docs/docs/datamodel.mdx, src/zepben/evolve/database/sqlite/readers/base_cim_reader.py, src/zepben/evolve/model/cim/iec61970/base/core/identified_object.py, src/zepben/evolve/model/cim/iec61970/base/core/name_type.py, src/zepben/evolve/services/common/translator/base_proto2cim.py, test/cim/collection_validator.py, test/cim/iec61970/base/core/test_identified_object.py, test/cim/iec61970/base/core/test_name_type.py, test/services/common/service_comparator_validator.py, test/services/common/test_base_service_comparator.py, test/services/common/translator/base_test_translator.py
Name rejig, but python
Breaking change is covered in the change log
=> Name rejig python equivalent

changelog.md, docs/docs/ewb_file_paths.mdx, docs/sidebars.js, src/zepben/evolve/__init__.py, src/zepben/evolve/database/paths/__init__.py, src/zepben/evolve/database/paths/database_type.py, src/zepben/evolve/database/paths/ewb_data_file_paths.py, test/database/paths/__init__.py, test/database/paths/test_ewb_data_file_paths.py
Mirror the functionality of EwbDataFilePaths it the jvm sdk. 
JVM version: https://github.com/zepben/evolve-sdk-jvm/pull/163
Helper class, all new functionality, not currently used by any of our code.
=> DEV-525 Add EwbDataFilePaths to python sdk

changelog.md, docs/docs/overview.md, docs/sidebars.js
Adds feature list to doco.
No blocking nor blocked tasks.
~- [ ] I have added/updated unit tests for these changes, and if not I have explained why they are not necessary.~ (No tests needed for doco change)
~- [ ] I have commented my code in any hard-to-understand or hacky areas.~
No breaking changes.
| Before | After |
| --- | --- |
| (No feature list) | ![image](https://github.com/zepben/ewb-sdk-python/assets/19983470/f6ae9421-e34b-4187-ab6c-8403af5200ad) |
=> DEV-894: Feature list

setup.py
No code changes, just an update to the dependencies which have no impact on the library.
* Updated to use gRPC library with renamed network state fields. 
* Removed obsolete `requests` dependency.
~- [ ] I have added/updated unit tests for these changes, and if not I have explained why they are not necessary.~
~- [ ] I have commented my code in any hard-to-understand or hacky areas.~
~- [ ] I have handled all new warnings generated by the compiler or IDE.~
~- [ ] I have rebased onto the target branch (usually main).~
~- [ ] I have updated the changelog.~
~- [ ] I have …
=> Updated to use gRPC library with renamed network state fields. 

setup.py, src/zepben/evolve/database/sqlite/tables/column.py, src/zepben/evolve/dataclassy/__init__.py, src/zepben/evolve/dataclassy/dataclass.py, src/zepben/evolve/dataclassy/decorator.py, src/zepben/evolve/dataclassy/functions.py, src/zepben/evolve/model/cim/iec61970/base/core/connectivity_node.py, src/zepben/evolve/model/cim/iec61970/base/core/identified_object.py, src/zepben/evolve/model/cim/iec61970/base/core/name_type.py, src/zepben/evolve/model/cim/iec61970/base/meas/value.py, src/zepben/evolve/services/common/meta/service_info.py, src/zepben/evolve/services/common/reference_resolvers.py, src/zepben/evolve/services/common/translator/base_proto2cim.py, src/zepben/evolve/services/network/tracing/connectivity/conducting_equipment_step.py, src/zepben/evolve/services/network/tracing/connectivity/connectivity_result.py, src/zepben/evolve/services/network/tracing/connectivity/limited_connected_equipment_trace.py, src/zepben/evolve/services/network/tracing/connectivity/xy_candidate_phase_paths.py, src/zepben/evolve/services/network/tracing/connectivity/xy_phase_step.py, src/zepben/evolve/services/network/tracing/feeder/remove_direction.py, src/zepben/evolve/services/network/tracing/find.py, src/zepben/evolve/services/network/tracing/phases/phase_step.py, src/zepben/evolve/services/network/tracing/traversals/tracker.py, src/zepben/evolve/services/network/tracing/traversals/traversal.py, src/zepben/evolve/streaming/get/consumer.py, src/zepben/evolve/streaming/get/hierarchy/data.py, src/zepben/evolve/streaming/get/network_consumer.py, src/zepben/evolve/streaming/grpc/grpc.py, test/conftest.py, test/services/common/test_base_service_comparator.py, test/streaming/grpc/test_grpc_channel_builder.py
Pulls dataclassy into the SDK at version 0.6.2 to fix a bug with `__repr__`
None
=> Vendor dataclassy and fix repr bug

changelog.md, src/zepben/evolve/streaming/get/network_consumer.py, test/streaming/get/test_network_consumer.py
Support NetworkState for `network_consumer` methods.
None
None
- ~[ ] I have commented my code in any hard-to-understand or hacky areas.~
- ~[ ] I have updated any documentation required for these changes.~
Not a breaking change.
=> [DEV-2210] Support NetworkState for get_equipment_container

docs/docs/consumer.mdx
there was no connection example error however there was a mistake in the "Network Hierarchy" example and I have fixed that in this PR.
List any other tasks / PRs that are required to be merged alongside this one (e.g. front end task for back end change or vice versa). If a PR exists, add a link. If not, just add an appropriate note here so reviewers know there is a dependency and will hold off merging until all things are ready.
Explain in detail how your reviewer can test the changes proposed in this PR. If it cannot be tested, leave an explanation on why.
Please leave a summary of the breaking changes here. This is useful for the reviewer, …
=> DEV-2162 Fix connection examples
