changelog.md
docs/docs/consumer.mdx
docs/docs/services.mdx
setup.py
src/zepben/evolve/__init__.py
src/zepben/evolve/model/cim/iec61970/base/core/identified_object.py
src/zepben/evolve/services/common/base_service.py
src/zepben/evolve/services/common/reference_resolvers.py
src/zepben/evolve/services/network/translator/__init__.py
src/zepben/evolve/services/network/translator/network_cim2proto.py
src/zepben/evolve/services/network/translator/network_proto2cim.py
src/zepben/evolve/streaming/get/consumer.py
src/zepben/evolve/streaming/get/network_consumer.py
src/zepben/evolve/util.py
test/network_fixtures.py
test/pb_creators.py
test/run_streaming.py
test/services/common/__init__.py
test/services/common/test_base_service.py
test/services/common/test_reference_resolver.py
test/test_consumer.py
test/test_network_to_cim.py
test/test_reference_resolvers.py
tox.ini

@charlta @gcarwardine 
So this PR does a few things but notably makes get_feeder resolve all references rather than the previous subset of types.
From what I understand Carlos isn't currently blocked on this as he has a workaround at the moment, so it's not a huge rush. It requires some thought and may be slightly controversial (although hopefully not)
The other big change is around unresolved references - I've changed them to be indexed in two ways: "from" and "to". 
The "to" map is an index over to_mrid (as it was previously) and there is now a new "from" map which has the reverse. Both maps always contain the same data, they are just indexed differently.
This allows for some more efficient querying of unresolved references, as you can easily get all the references for an object by its …

Proj 270 get feeder resolve all references

---

README.md
changelog.md
setup.py
src/zepben/evolve/model/cim/iec61970/base/core/terminal.py
src/zepben/evolve/services/common/base_service.py
src/zepben/evolve/services/network/tracing/phases/phasing.py
src/zepben/evolve/services/network/tracing/util.py
src/zepben/evolve/services/network/translator/network_proto2cim.py
src/zepben/evolve/streaming/get/consumer.py
src/zepben/evolve/streaming/get/customer_consumer.py
src/zepben/evolve/streaming/get/diagram_consumer.py
src/zepben/evolve/streaming/get/network_consumer.py
test/catching_thread.py
test/run_streaming.py
test/services/common/test_base_service.py
test/services/network/test_network_extensions.py
test/streaming/get/mock_server.py
test/streaming/get/test_consumer.py
test/streaming/get/test_network_consumer.py
tox.ini

* Updated consumer clients to handle a service rather than each method requiring one.
* Changed to use streaming gRPC calls
* Reworked testing to use in-memory server mock rather than stub mocks to reveal issues with packing/unpacking grpc messages.
* Various small fixes revealed by changing tests.

PROJ-524 - Major rework

---

src/zepben/evolve/streaming/grpc/connect.py

This is a common use case in all the sdk demos, so instead of making the end user jump through hoops and define and pass in their own `ZepbenAuthenticator`, they can simply pass in a `username` and `password` instead, and the appropriate authenticator will be constructed for them.

Add username and password authentication option to connect_async

---

changelog.md
docs/docs/consumer.mdx
src/zepben/evolve/streaming/grpc/connect.py

This adds an extra boolean argument to connect `secure` that must be set
to true whenever a secure or authenticated connection is required.

Default arg for ca now causes OS certs to be used.

---

src/zepben/evolve/streaming/grpc/channel_builder.py
src/zepben/evolve/streaming/grpc/connect.py

`grpc.aio.Channel` can be `async with`'d, meaning we don't need to make our own context managers.

EWB-1239 - Fix grpc connection functions

---

src/zepben/evolve/services/network/network.py
src/zepben/evolve/services/network/tracing/connectivity.py
src/zepben/evolve/testing/test_network_builder.py
test/testing/__init__.py
test/testing/test_test_network_builder.py

* Fixed issues with terminal connectivity revealed while testing the `TestNetworkBuilder`
* Added support for `PowerTransformers` and generic `ConductingEquipment` to `TestNetworkBuilder`. Added tests and fixed issues revealed.

PROJ-2265 - Add `PowerTransformer` to `TestNetworkBuilder`

---

changelog.md
src/zepben/evolve/model/busbranch/bus_branch.py
test/busbranch/test_bus_branch.py

Signed-off-by: Jimmy Tung <jimmy.tung@zepben.com>

Order terminals on head feeder so bus containing source is always first

---

changelog.md
src/zepben/evolve/database/sqlite/database_reader.py
src/zepben/evolve/services/network/tracing/connectivity/connectivity_result.py
src/zepben/evolve/services/network/tracing/phases/remove_phases.py
src/zepben/evolve/services/network/tracing/phases/set_phases.py
src/zepben/evolve/services/network/tracing/queuing_functions.py
src/zepben/evolve/testing/test_network_builder.py
test/services/network/tracing/phases/test_set_phases.py
test/services/network/tracing/phases/util.py
test/testing/test_test_network_builder.py

* `SetPhases` now supports setting backwards through XN/XY transformers
* Removed `get_connectivity` and `get_connected_equipment` from `connectivity_result.py`

EWB-1458 - `SetPhases` now supports setting backwards through XN/XY transformers

---

changelog.md
docs/docs/consumer.mdx
src/zepben/evolve/streaming/get/network_consumer.py
test/network_fixtures.py
test/streaming/get/test_network_consumer.py

This is the Python version of the change in https://github.com/zepben/evolve-sdk-jvm/pull/116. The helper function `get_equipment_container` is used in the python sdk examples and this will allow for an easier transition.
- None
- https://github.com/zepben/pp-translator/pull/17
- https://github.com/zepben/python-sdk-examples/pull/14

EWB-1855: Add linked container params for get_equipment_container

---

changelog.md
setup.py
src/zepben/evolve/services/network/translator/network_proto2cim.py
src/zepben/evolve/streaming/grpc/connect.py
test/services/network/translator/test_network_translator.py

Ensures correct order of transformer ends in `tx.ends`, where `tx` is a `PowerTransformer` translated from protobuf. See https://app.clickup.com/t/369vbur for more details.
- None
- https://github.com/zepben/edith-sdk/pull/2

Translate TransformerEnd fields before associating PTE with PT

---

src/zepben/evolve/model/cim/iec61970/base/auxiliaryequipment/potential_transformer_kind.py

Adds missing licence header comment to `potential_transformer_kind.py`.
- None
- None (licence check is being skipped on other branches)

EWB-2540: Add missing licence

---

changelog.md
src/zepben/evolve/__init__.py
src/zepben/evolve/services/network/tracing/connectivity/conducting_equipment_step_tracker.py
src/zepben/evolve/services/network/tracing/connectivity/connectivity_tracker.py
src/zepben/evolve/services/network/tracing/feeder/associated_terminal_tracker.py
src/zepben/evolve/services/network/tracing/phases/phase_step_tracker.py
src/zepben/evolve/services/network/tracing/traversals/basic_tracker.py
src/zepben/evolve/services/network/tracing/traversals/tracker.py
src/zepben/evolve/services/network/tracing/tree/downstream_tree.py
src/zepben/evolve/services/network/tracing/tree/tree_node.py
src/zepben/evolve/services/network/tracing/tree/tree_node_tracker.py
test/services/network/test_data/looping_network.py
test/services/network/tracing/connectivity/test_conducting_equipment_step_tracker.py
test/services/network/tracing/connectivity/test_connectivity_tracker.py
test/services/network/tracing/phases/test_phase_step_tracker.py
test/services/network/tracing/traversals/test_basic_tracker.py
test/services/network/tracing/traversals/test_tracker.py
test/services/network/tracing/tree/__init__.py
test/services/network/tracing/tree/test_downstream_trace.py
test/services/network/tracing/tree/test_downstream_tree.py
test/services/network/tracing/tree/test_tree_node.py
test/services/network/tracing/tree/test_tree_node_tracker.py

- Add missing `run` method for `DownstreamTree`
- Add missing `TreeNodeTracker`
- Separate classes into their own files for `tree` submodule
- Add tests for `tree` submodule
- None
- https://github.com/zepben/pp-translator/pull/19
- https://github.com/zepben/edith-sdk/pull/3

EWB-2592: Fix downstream trees

---

changelog.md
src/zepben/evolve/services/network/tracing/tracing.py
test/services/network/tracing/test_tracing.py
test/services/network/tracing/tree/test_downstream_tree.py
test/services/network/tracing/tree/test_tree_node_tracker.py

Adds method names currently missing from `__all__` in `tracing.py`. Also updates test to include all public methods in `test_suppliers()`.
- None
- https://github.com/zepben/edith-sdk/pull/3
- https://github.com/zepben/pp-translator/pull/19

Add missing methods to __all__ in tracing.py

---

src/zepben/evolve/streaming/grpc/auth_token_plugin.py
test/streaming/grpc/test_auth_token_plugin.py

gRPC gives "invalid metadata" unless the auth header is exactly "authorization" without capital letters. This fixes the issue.
- None
- None
Tasks mirroring this one:
- Investigate issue in JVM gRPC connection functions (TBA)

EWB-3257: Fix capitalization for auth header name

---

changelog.md
src/zepben/evolve/streaming/get/network_consumer.py
test/network_fixtures.py
test/streaming/get/mock_server.py
test/streaming/get/test_network_consumer.py

Stops the client from pulling in equipment for edge containers - e.g an open switch with 2 LvFeeders.
These are always required, if you do not do them, reviewers will be angry:
These you can remove from the list if they are not applicable for this PR.

Ewb 3454 dont resolve container equipment

---

changelog.md
src/zepben/evolve/__init__.py
src/zepben/evolve/database/sqlite/database_writer.py
src/zepben/evolve/model/cim/iec61970/base/core/phase_code.py
src/zepben/evolve/model/cim/iec61970/base/wires/single_phase_kind.py
src/zepben/evolve/services/network/tracing/connectivity/transformer_phase_paths.py
src/zepben/evolve/services/network/tracing/feeder/set_direction.py
src/zepben/evolve/services/network/tracing/traversals/traversal.py
src/zepben/evolve/testing/test_network_builder.py
test/cim/iec61970/base/core/test_phase_code.py
test/cim/iec61970/base/wires/test_single_phase_kind.py
test/services/network/tracing/connectivity/test_terminal_connectivity_internal.py
test/services/network/tracing/feeder/test_set_direction.py
test/services/network/tracing/phases/test_set_phases.py
test/services/network/tracing/traversals/test_basic_traversal.py
test/testing/test_test_network_builder.py

* Added support for LV2 below SWER transformers.
* Improved logging when saving a database.
* The `TestNetworkBuilder` has been enhanced with the following features:
* You can now set the ID's without having to create a customer 'other' creator.
* Added inbuilt support for `EnergyConsumer`
* The `to*` and `connect` functions can specify the connectivity node mRID to use.
* `Traversal` has two new helper methods:
* `if_not_stopping`: Adds a step action that is only called if the traversal is not stopping on the item.
* `if_stopping`: Adds a step action that is only called if the traversal is stopping on the item.
* `SetDirection.run(NetworkService)` will no longer set directions for feeders with a head terminal on an open switch.
* Feeder directions are now stopped at substation …

EWB-3793: LV2 support and trace enhancements

---

.idea/codeStyles/Project.xml
CONTRIBUTING.md
changelog.md
src/zepben/evolve/streaming/exceptions.py
src/zepben/evolve/streaming/grpc/connect.py
src/zepben/evolve/streaming/grpc/grpc_channel_builder.py
test/streaming/grpc/test_connect.py
test/streaming/grpc/test_grpc_channel_builder.py

Newly created grpc channels don't report any type of connection error until a grpc request is actually attempted. This PR attempts a getMetadata() grpc request on any newly created grpc channels and on failure throws an exception rather than returning an unusable channel to the user. 
Relies on  https://github.com/zepben/evolve-sdk-python/pull/135
Jvm sdk equivalent https://github.com/zepben/evolve-sdk-jvm/pull/150
GrpcChannelBuilder requires the server it's connecting to have at least one of the following: NetwokConsumerService, CustomerConsumerService, DiagramConsumerSerivce runing and permissions to call getMetadata() on it. …

EWB-2452 Verify gRPC connections at channel creation time

---

changelog.md
src/zepben/evolve/model/cim/iec61970/base/core/equipment_container.py
test/cim/iec61970/base/core/test_feeder.py

Update the assign feeder head terminal behaviour in the Python SDK to match the JVM SDK. 
The difference being that the JVM SDK allows updating/re-assigning (after initial assignment) of the feeder head terminal when the feeder contains no equipment(or current equipment)

EWB-4143 Update Assigning Feeder Head Terminal to Match JVM SDK

---

.gitignore
changelog.md
src/zepben/evolve/streaming/grpc/grpc_channel_builder.py
test/streaming/grpc/test_grpc_channel_builder.py

* Default grpc channel message size is now 20MB.
We need to be able to pass configuration grpc channel options to control things like for example the max message size. This PR adds support for this.
NONE
This is not a breaking change.

Added support for passing the grpc channel configuration options to the `GrpcChannelBuilder`.

---

.gitignore
changelog.md
src/zepben/evolve/streaming/grpc/connect.py
src/zepben/evolve/streaming/grpc/grpc_channel_builder.py
test/streaming/grpc/test_grpc_channel_builder.py

* Default grpc channel message size is now 20MB.
Signed-off-by: Roberto Marquez <roberto.marquez@zepben.com>
Co-authored-by: Kurt Greaves <kurt.greaves@zepben.com>
(cherry picked from commit 74c3457dca02cf073e916ebddb9ce1cf553cf21b)
Signed-off-by: Roberto Marquez <roberto.marquez@zepben.com>
This PR cherrypicks the changes from main that add support for passing in grpc channel options.
NONE
Not a breaking change.

Added support for passing the grpc channel configuration options to the `GrpcChannelBuilder`. (#145)

---

changelog.md
src/zepben/evolve/streaming/get/network_consumer.py
test/streaming/get/pb_creators.py

Fixed issue where `PotentialTransformer`'s couldn't be deserialized from gRPC/protobuf messages because the type was missing from the `_nio_type_to_cim` list.
If you have added new dependencies to the project please state why. 
No other work required
~- [] I have commented my code in any hard-to-understand or hacky areas.~
~- [ ] I have handled all new warnings generated by the compiler or IDE.~
Fix only allows additional functionality. Shouldn't prevent or change any existing behaviour.

DEV-249 Include PotentialTransformers in serialized types list

---

changelog.md
src/zepben/evolve/database/sqlite/common/metadata_collection_reader.py
src/zepben/evolve/database/sqlite/common/metadata_collection_writer.py
src/zepben/evolve/database/sqlite/common/metadata_entry_reader.py
src/zepben/evolve/database/sqlite/customer/customer_database_reader.py
src/zepben/evolve/database/sqlite/customer/customer_database_writer.py
src/zepben/evolve/database/sqlite/diagram/diagram_database_reader.py
src/zepben/evolve/database/sqlite/diagram/diagram_database_writer.py
src/zepben/evolve/database/sqlite/network/network_database_reader.py
src/zepben/evolve/database/sqlite/network/network_database_writer.py
src/zepben/evolve/services/common/base_service.py
src/zepben/evolve/services/common/meta/metadata_collection.py
src/zepben/evolve/services/customer/customers.py
src/zepben/evolve/services/diagram/diagrams.py
src/zepben/evolve/services/measurement/measurements.py
src/zepben/evolve/services/network/network_service.py
src/zepben/evolve/services/services.py
test/database/sqlite/common/cim_database_schema_common_tests.py
test/database/sqlite/customer/test_customer_database_reader.py
test/database/sqlite/customer/test_customer_database_schema.py
test/database/sqlite/diagram/test_diagram_database_reader.py
test/database/sqlite/diagram/test_diagram_database_schema.py
test/database/sqlite/network/test_network_database_reader.py
test/database/sqlite/network/test_network_database_schema.py
test/services/common/test_base_service.py
test/services/test_services.py

Added `Services` class, added `MetadataCollection` to base services and updated database readers/writers to use relocated metadata.
Side effect of doing this was changing `BaseService` and `MetadataCollection` to no longer implement `dataclassy.dataclass` in order to get a separate instance of the metadata per service instance.
* Database readers and writes for each `BaseService` no longer accept a `MetadataCollection`.
* `BaseService` and `MetadataCollection` are no longer dataclassy dataclasses.

[DEV-1776] Added `Services` class, added `MetadataCollection` to base services

---

changelog.md
docs/docs/query-network-state-client.mdx
docs/docs/query-network-state-service.mdx
docs/docs/update-network-state-client.mdx
docs/docs/update-network-state-service.mdx
docs/sidebars.js
src/zepben/evolve/__init__.py
src/zepben/evolve/streaming/data/__init__.py
src/zepben/evolve/streaming/data/current_state_event.py
src/zepben/evolve/streaming/data/set_current_states_status.py
src/zepben/evolve/streaming/get/query_network_state_client.py
src/zepben/evolve/streaming/get/query_network_state_service.py
src/zepben/evolve/streaming/mutations/__init__.py
src/zepben/evolve/streaming/mutations/update_network_state_client.py
src/zepben/evolve/streaming/mutations/update_network_state_service.py
src/zepben/evolve/util.py
test/streaming/data/__init__.py
test/streaming/data/test_current_state_event.py
test/streaming/data/test_set_current_states_status.py
test/streaming/get/test_query_network_state_client.py
test/streaming/get/test_query_network_state_service.py
test/streaming/mutations/__init__.py
test/streaming/mutations/test_update_network_state_client.py
test/streaming/mutations/test_update_network_state_service.py
test/util.py

Service and client classes to provide simplified interface for updating and querying network states. 
The clients and services are implemented to be asynchronous. Because the callback for `UpdateNetworkStateService` is also asynchronous, `SetCurrentStatesStatus` was made to have a batch id and the callback accept a batch id and collection of events.
None
Test by using the interface.
None

[DEV-1521] Added network state clients/services

---

changelog.md
docs/docs/consumer.mdx
src/zepben/evolve/streaming/grpc/connect.py
src/zepben/evolve/streaming/grpc/grpc_channel_builder.py
test/streaming/grpc/test_connect.py
test/streaming/grpc/test_grpc_channel_builder.py

This PR adds new feature that allows the SDK to connect using personal access tokens generated by the Evolve App Server or the Evolve Web Client.
n/a
A token can be generated from the EAS app. The EAS web client now supports creating user access tokens. To create machine tokens use [this front-end branch](https://github.com/zepben/evolve-web-app/pull/193). 
- ~[ ] I have considered if this is a breaking change and will communicate it with other team members if so.~
Please leave a summary of the breaking changes here. This is useful for the reviewer, but also is useful for communication to the team when merged (e.g. you could copy and paste …

DEV-1298 [PAT] Update python-sdk for PAT service

---

changelog.md
docs/docs/query-network-state-client.mdx
docs/docs/update-network-state-client.mdx
docs/versioned_docs/version-0.42.0/query-network-state-client.mdx
docs/versioned_docs/version-0.42.0/update-network-state-client.mdx
setup.py
src/zepben/evolve/__init__.py
src/zepben/evolve/streaming/data/current_state_event_batch.py
src/zepben/evolve/streaming/data/set_current_states_status.py
src/zepben/evolve/streaming/get/query_network_state_client.py
src/zepben/evolve/streaming/get/query_network_state_service.py
src/zepben/evolve/streaming/mutations/update_network_state_client.py
test/streaming/data/test_set_current_states_status.py
test/streaming/get/test_query_network_state_client.py
test/streaming/get/test_query_network_state_service.py
test/streaming/mutations/test_update_network_state_client.py
test/streaming/mutations/test_update_network_state_service.py

* Renamed `UpdateNetworkStateClient.SetCurrentStatesRequest` to `CurrentStateEventBatch`. You will need to update any uses, but the class members are the same.
* Removed `ProcessingPaused` current state response message as this functionality won't be supported.
* `QueryNetworkStateClient.get_current_states` now returns a `CurrentStateEventBatch` rather than just the events themselves.
* `QueryNetworkStateService.on_get_current_states` must now return a stream of `CurrentStateEventBatch` rather than just the events themselves.
* Added `BatchNotProcessed` current state response. This is used to indicate a batch has been ignored, rather than just returning a `BatchSuccessful`.
* `QueryNetworkStateService` now supports `reportBatchStatus`, which requires two new constructor callbacks:
* …

[DEV-2041] Additional current state status processing

---

changelog.md
src/zepben/evolve/model/cim/iec61970/base/core/equipment_container.py
src/zepben/evolve/model/cim/iec61970/infiec61970/feeder/lv_feeder.py
src/zepben/evolve/services/common/reference_resolvers.py
src/zepben/evolve/services/common/resolver.py
src/zepben/evolve/services/network/network_service_comparator.py
src/zepben/evolve/services/network/translator/network_cim2proto.py
src/zepben/evolve/services/network/translator/network_proto2cim.py
src/zepben/evolve/streaming/get/network_consumer.py
test/cim/cim_creators.py
test/cim/iec61970/base/core/test_feeder.py
test/cim/iec61970/infiec61970/feeder/test_lv_feeder.py
test/services/network/test_network_service_comparator.py
test/streaming/get/test_network_consumer.py

Pulled in current state container enhancement from `ewb-grpc`. Modified NetworkConsumerClient to support the rpc changes. Also, Feeder and LvFeeder CIM model have been added with their current network state association.
~This PR can be reviewed but will fail to build until this [task](https://app.clickup.com/t/6929263/DEV-2041) has been merged and this branch rebased. This [PR](https://github.com/zepben/ewb-grpc/pull/121) will also need to be merged in and the `zepben.protobuf` version updated.~
- ~https://github.com/zepben/ewb-grpc/pull/121~
- ~https://github.com/zepben/ewb-sdk-python/pull/165 (for https://app.clickup.com/t/6929263/DEV-2041)~
- https://github.com/zepben/ewb-sdk-python/pull/162
None.
If any of these are not applicable, strikethrough the line `~like this~`. **Do not delete …

[DEV-1977] current states container enhancement

---

changelog.md
setup.py
src/zepben/evolve/services/network/tracing/feeder/feeder_direction.py
test/services/network/tracing/feeder/test_feeder_direction.py

Supports FeederDirection.CONNECTOR to provide support for BusbarSections that now have only one terminal
I sincerely hope this won't break anything with older EWBs.

Add FeederDirection.CONNECTOR for BusbarSection use

---

changelog.md
docs/docs/query-network-state-client.mdx
docs/docs/query-network-state-service.mdx
src/zepben/evolve/streaming/get/query_network_state_client.py
test/streaming/get/mock_server.py
test/streaming/get/test_network_consumer.py
test/streaming/get/test_query_network_state_client.py

* Added `QueryNetworkStateClient.reportBatchStatus` support.
* Fixed errors in gRPC mock server testing.
Covered by unit tests, or you can use it to send a status response to a service you have written...
Non-breaking.

[DEV-2418] Add `QueryNetworkStateClient.reportBatchStatus` support.

---

changelog.md
docs/docs/update-network-state-client.mdx
src/zepben/evolve/streaming/data/current_state_event.py
test/run_streaming.py
test/streaming/data/test_current_state_event.py

Added the missing current state events:
* `AddCutEvent`
* `RemoveCutEvent`
* `AddJumperEvent`
* `RemoveJumperEvent`
They had previously been added to the protobuf messages, but were not added to our wrappers.
None.
Non-breaking

[DEV-2674] Added support for `AddCutEvent`, `RemoveCutEvent`, `AddJumperEvent` and `RemoveJumperEvent`

---

changelog.md
setup.py
src/zepben/evolve/__init__.py
src/zepben/evolve/database/sqlite/network/network_cim_reader.py
src/zepben/evolve/database/sqlite/network/network_cim_writer.py
src/zepben/evolve/database/sqlite/network/network_database_tables.py
src/zepben/evolve/database/sqlite/network/network_service_reader.py
src/zepben/evolve/database/sqlite/tables/associations/table_assets_power_system_resources.py
src/zepben/evolve/database/sqlite/tables/table_version.py
src/zepben/evolve/model/cim/iec61968/assets/asset.py
src/zepben/evolve/model/cim/iec61970/base/core/power_system_resource.py
src/zepben/evolve/model/cim/iec61970/base/wires/regulating_control.py
src/zepben/evolve/services/common/reference_resolvers.py
src/zepben/evolve/services/common/resolver.py
src/zepben/evolve/services/network/network_service_comparator.py
src/zepben/evolve/services/network/translator/network_cim2proto.py
src/zepben/evolve/services/network/translator/network_proto2cim.py
test/cim/cim_creators.py
test/cim/iec61968/assets/test_asset.py
test/cim/iec61970/base/core/test_power_system_resource.py
test/database/sqlite/schema_utils.py
test/services/network/test_network_service_comparator.py
test/services/network/translator/test_network_translator.py
test/streaming/get/grpcio_aio_testing/mock_async_channel.py
test/streaming/get/pb_creators.py

Support asset -> PSR relationship to enable linking poles to their equipment.
Spin up jemena database, pull down a feeder, and try extract the PSRs from the poles.
Not breaking, really. However this will also incorporate protobuf and gRPC upgrades, which might probably be breaking.

[DEV-2391] Support Asset -> PowerSystemResource relationship

---

src/zepben/ewb/model/cim/extensions/iec61970/base/protection/power_direction_kind.py
src/zepben/ewb/model/cim/extensions/iec61970/base/protection/protection_kind.py
src/zepben/ewb/model/cim/extensions/iec61970/base/wires/battery_control_mode.py
src/zepben/ewb/model/cim/extensions/iec61970/base/wires/transformer_cooling_type.py
src/zepben/ewb/model/cim/extensions/iec61970/base/wires/vector_group.py
src/zepben/ewb/model/cim/iec61968/assetinfo/wire_material_kind.py
src/zepben/ewb/model/cim/iec61968/customers/customer_kind.py
src/zepben/ewb/model/cim/iec61968/infiec61968/infassetinfo/transformer_construction_kind.py
src/zepben/ewb/model/cim/iec61968/infiec61968/infassetinfo/transformer_function_kind.py
src/zepben/ewb/model/cim/iec61968/infiec61968/infassets/streetlight_lamp_kind.py
src/zepben/ewb/model/cim/iec61968/metering/controlled_appliance.py
src/zepben/ewb/model/cim/iec61968/metering/end_device_function_kind.py
src/zepben/ewb/model/cim/iec61970/base/auxiliaryequipment/potential_transformer_kind.py
src/zepben/ewb/model/cim/iec61970/base/core/phase_code.py
src/zepben/ewb/model/cim/iec61970/base/diagramlayout/diagram_style.py
src/zepben/ewb/model/cim/iec61970/base/diagramlayout/orientation_kind.py
src/zepben/ewb/model/cim/iec61970/base/domain/unit_symbol.py
src/zepben/ewb/model/cim/iec61970/base/generation/production/battery_state_kind.py
src/zepben/ewb/model/cim/iec61970/base/wires/phase_shunt_connection_kind.py
src/zepben/ewb/model/cim/iec61970/base/wires/regulating_control_mode_kind.py
src/zepben/ewb/model/cim/iec61970/base/wires/single_phase_kind.py
src/zepben/ewb/model/cim/iec61970/base/wires/svc_control_mode.py
src/zepben/ewb/model/cim/iec61970/base/wires/synchronous_machine_kind.py
src/zepben/ewb/model/cim/iec61970/base/wires/winding_connection.py
src/zepben/ewb/services/network/network_state.py
src/zepben/ewb/streaming/get/included_energized_containers.py
src/zepben/ewb/streaming/get/included_energizing_containers.py

@unique was messing with type hints, also not really needed

---

changelog.md
src/zepben/ewb/services/network/tracing/networktrace/actions/equipment_tree_builder.py
src/zepben/ewb/services/network/tracing/networktrace/actions/tree_node.py
test/services/network/tracing/networktrace/actions/test_equipment_tree_builder.py
test/services/network/tracing/networktrace/test_network_trace.py

A summary of the changes and what they achieve. If there is a ClickUp task with decent detail associated with this change the summary can be brief, otherwise please add some motivation and context here.
If you have added new dependencies to the project please state why.
List any other tasks / PRs that are required to be merged alongside this one (e.g. front end task for back end change or vice versa). If a PR exists, add a link. If not, just add an appropriate note here so reviewers know there is a dependency and will hold off merging until all things are ready.
Explain in detail how your reviewer can test the changes proposed in this PR. If it cannot be tested, leave an explanation on why.
If any of these are not applicable, strikethrough the line `~like this~`. **Do not delete it!**. …

Dev 3524 - equipment tree builder leaves

---

CONTRIBUTING.md
src/zepben/ewb/services/common/translator/base_cim2proto.py
src/zepben/ewb/services/common/translator/base_proto2cim.py
src/zepben/ewb/services/common/translator/util.py
src/zepben/ewb/services/network/translator/network_cim2proto.py
src/zepben/ewb/services/network/translator/network_proto2cim.py

@with_network_service_or_none can be pulled out if its contentious.
List any other tasks / PRs that are required to be merged alongside this one (e.g. front end task for back end change or vice versa). If a PR exists, add a link. If not, just add an appropriate note here so reviewers know there is a dependency and will hold off merging until all things are ready.
Explain in detail how your reviewer can test the changes proposed in this PR. If it cannot be tested, leave an explanation on why.
- [ x] I have performed a self review of my own code (including checking issues raised when creating the PR).
- [ x] I have added/updated unit tests for …

slight refactor of proto2cim and cim2proto

---

.github/workflows/python-lib-release.yml

Just run a proper flow for releases. It was updated to work with the new Python build project structure properly.

Use new release flow when releasing
